twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        URL_SITE: '%env(URL_SITE)%'
        site_name: 'Secret-Santa'
    
when@test:
    twig:
        strict_variables: true
